export const homeAbout = [
  {
    id: 1,
    cover: "https://img.icons8.com/dotty/80/000000/storytelling.png",
    title: "Online Courses",
    desc: "Learn at your own pace, anytime, anywhere.",
  },
 
  {
    id: 2,
    cover: "https://img.icons8.com/ios/80/000000/athlete.png",
    title: "Learn with Expert",
    desc: " Access courses and experts from around the world.",
  },
  {
    id: 3,
    cover: "https://img.icons8.com/ios/80/000000/athlete.png",
    title: "Learn with Expert",
    desc: "Save on transportation, accommodation, and textbook costs.",
  },
]
export const awrapper = [
  {
    cover: "https://img.icons8.com/external-yogi-aprelliyanto-basic-outline-yogi-aprelliyanto/80/ffffff/external-graduation-education-yogi-aprelliyanto-basic-outline-yogi-aprelliyanto.png",
    data: "4.8/5",
    title: "From 1000+ mentees",
  },
 {
    cover: "https://img.icons8.com/external-outline-icons-maxicons/80/ffffff/external-calender-insurance-outline-outline-icons-maxicons.png",
    data: "100 Million+",
    title: "Total minutes spend",
  },
  {
    cover: "https://img.icons8.com/ios/80/ffffff/macbook-idea--v3.png",
    data: "21,360+",
    title: "Satisfied Mentees ",
  },
]
export const coursesCard = [
  {
    id: 1,
    cover: "../images/courses/c1.png",
    coursesName: "Introducing to Software Engineering",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by John Smith",
        totalTime: "50 lectures (190 hrs)",
      },
    ],
    priceAll: "$100 All Course",
    pricePer: "$15 per month",
  },
  {
    id: 2,
    cover: "../images/courses/c2.png",
    coursesName: "Enhancing Adobe Photoshop CC 2020 Skills",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Ram Gurung",
        totalTime: "30 lectures (125 hrs)",
      },
    ],
    priceAll: "$200 All Course",
    pricePer: "$25 per month",
  },
  {
    id: 3,
    cover: "../images/courses/c3.png",
    coursesName: "HTML, CSS, and Javascript for Web Developers",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Saroj Nepal",
        totalTime: "50 lectures (50 hrs)",
      },
    ],
    priceAll: "$50 All Course",
    pricePer: "$5 per month",
  },
  {
    id: 4,
    cover: "../images/courses/c4.png",
    coursesName: "Introducing to Programming with WordPress",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Prabin Thapa Mager",
        totalTime: "20 lectures (20 hrs)",
      },
    ],
    priceAll: "$30 All Course",
    pricePer: "$3 per month",
  },
  {
    id: 5,
    cover: "../images/courses/c5.png",
    coursesName: "Introducing to Programming with ReactJS",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Sunil Bishowkaram",
        totalTime: "100 lectures (150 hrs)",
      },
    ],
    priceAll: "$300 All Course",
    pricePer: "$30 per month",
  },
  {
    id: 6,
    cover: "../images/courses/c6.png",
    coursesName: "Learn Frontend Programming Language",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Sunil Bishowkaram",
        totalTime: "200 lectures (300 hrs)",
      },
    ],
    priceAll: "$500 All Course",
    pricePer: "$80 per month",
  },
  {
    id: 7,
    cover: "../images/courses/c7.png",
    coursesName: "Introducing to with HTML / CSS",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Price",
        totalTime: "20 lectures (50 hrs)",
      },
    ],
    priceAll: "$20 All Course",
    pricePer: "$2 per month",
  },
  {
    id: 8,
    cover: "../images/courses/c8.png",
    coursesName: "Introducing to with JAVA",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Petter",
        totalTime: "80 lectures (200 hrs)",
      },
    ],
    priceAll: "$200 All Course",
    pricePer: "$40 per month",
  },
  {
    id: 9,
    cover: "../images/courses/c9.png",
    coursesName: "Introducing to with HTML / CSS / JAVASCRIPT",
    courTeacher: [
      {
        dcover: "./images/back.webp",
        name: "by Petter",
        totalTime: "50 lectures (50 hrs)",
      },
    ],
    priceAll: "$20 All Course",
    pricePer: "$3 per month",
  },
]
export const online = [
  {
    cover: "./images/courses/online/o1.png",
    hoverCover: "./images/courses/online/o1.1.png",
    courseName: "UI/UX Design Mentors",
    course: "25 Mentors",
  },
  {
    cover: "./images/courses/online/o2.png",
    hoverCover: "./images/courses/online/o2.1.png",
    courseName: "Engineering Fronend",
    course: "25 Mentors",
  },
  {
    cover: "./images/courses/online/o3.png",
    hoverCover: "./images/courses/online/o3.1.png",
    courseName: "Engineering backend",
    course: "10 Mentors",
  },
  {
    cover: "./images/courses/online/o4.png",
    hoverCover: "./images/courses/online/o4.1.png",
    courseName: "Engineering full stack",
    course: "15 Mentors",
  },
  {
    cover: "./images/courses/online/o5.png",
    hoverCover: "./images/courses/online/o5.1.png",
    courseName: "Data science",
    course: "30 Mentors",
  },
  {
    cover: "./images/courses/online/o6.png",
    hoverCover: "./images/courses/online/o6.1.png",
    courseName: "Business",
    course: "60 Mentors",
  },
  // {
  //   cover: "./images/courses/online/o7.png",
  //   hoverCover: "./images/courses/online/o7.1.png",
  //   courseName: "Health & Fitness",
  //   course: "10 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o8.png",
  //   hoverCover: "./images/courses/online/o8.1.png",
  //   courseName: "Marketing",
  //   course: "30 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o9.png",
  //   hoverCover: "./images/courses/online/o9.1.png",
  //   courseName: "Graphic Design",
  //   course: "80 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o10.png",
  //   hoverCover: "./images/courses/online/o10.1.png",
  //   courseName: "Music",
  //   course: "120 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o11.png",
  //   hoverCover: "./images/courses/online/o11.1.png",
  //   courseName: "Business Administration",
  //   course: "17 Courses",
  // },
  // {
  //   cover: "./images/courses/online/o12.png",
  //   hoverCover: "./images/courses/online/o12.1.png",
  //   courseName: "Web Management",
  //   course: "17 Courses",
  // },
]
export const team = [
  {
    cover: "./images/team/t1.webp",
    name: "Ph.D Adrian Molises",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t2.webp",
    name: "Ph.D Arthur MaGregor",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t3.webp",
    name: "Ph.D Anna Hanzen",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t4.webp",
    name: "Ph.D Brian Wooden",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t5.webp",
    name: "Ph.D Adrian Molises",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t6.webp",
    name: "Ph.D Arthur MaGregor",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t7.webp",
    name: "Ph.D Anna Hanzen",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
  {
    cover: "./images/team/t8.webp",
    name: "Ph.D Brian Wooden",
    work: "DEVELOPER AND LEAD INSTRUCTOR",
  },
]
export const price = [
  {
    name: "BASIC PLAN",
    price: "49K",
    desc: "Q1 How do I access my course materials?",
  },
  {
    name: "BEGINNER PLAN",
    price: "79K",
    desc: "Q2 How long do I have to complete a course? ",
  },
  {
    name: "PREMIUM PLAN",
    price: "109k",
    desc: "Q3 Can I take a course at my own pace?",
  },
  {
    name: "ULTIMATE PLAN",
    price: "149K",
    desc: "What are the system requirements for online learning?",
  },
]
export const faq = [
  {
    title: "How to Enroll This Online Courses?",
    desc: "This is the first item's accordion body. It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "Where It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "How It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "How to Enroll This Online Courses?",
    desc: "This is the first item's accordion body. It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "Where It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
  {
    title: "How It is hidden by default, until the collapse?",
    desc: "It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. It's also worth noting that just about any HTML can go within the .accordion-body, though the transition does limit overflow.",
  },
]
export const blog = [
  {
    id: 1,
    title: "Build your Dream Software & Engineering Career",
    desc: " Determine what you want to achieve through online learning. What skills do you want to acquire? What topics do you want to explore? What are your career goals?",
    cover: "../images/blog/b1.webp",
  },
  {
    id: 2,
    title: "Build your Dream Software & Engineering Career",
    desc: "Select a suitable online learning platform that aligns with your goals. Popular options include MOOCs (Massive Open Online Courses) like Coursera, edX, and Udemy, as well as online courses and tutorials on YouTube, LinkedIn Learning, and Skillshare.",
    cover: "../images/blog/b2.webp",
  },
  {
    id: 3,
    title: "Build your Dream Software & Engineering Career",
    desc: "Create a dedicated learning space with a stable internet connection, a comfortable workspace, and minimal distractions. Ensure you have the necessary hardware and software to access your chosen platform and complete coursework.",
    cover: "../images/blog/b3.webp",
  },
  {
    id: 3,
    type: "admin",
    date: "JAN. 02, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b4.webp",
  },
  {
    id: 5,
    type: "admin",
    date: "DEC. 14, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b5.webp",
  },
  {
    id: 6,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 7,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 8,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 9,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 10,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 11,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 12,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 13,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Step 1",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 14,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Step 2",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
  {
    id: 15,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "step 3",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
]
export const testimonal = [
  {
    id: 1,
    name: "ROGER SCOTT",
    post: "MICROSOFT",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t1.webp",
  },
  {
    id: 2,
    name: "ROGER SCOTT",
    post: " GOOGLE",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t2.webp",
  },
  {
    id: 3,
    name: "ROGER SCOTT",
    post: "SALESFORCE",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t1.webp",
  },
  {
    id: 4,
    name: "ROGER SCOTT",
    post: "PAYPAL",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t3.webp",
  },
  {
    id: 5,
    name: "ROGER SCOTT",
    post: "HUBBINS",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t1.webp",
  },
  {
    id: 6,
    name: "ROGER SCOTT",
    post: "GOLDMAN SACH",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t3.webp",
  },
  {
    id: 7,
    name: "ROGER SCOTT",
    post: "MEESHO",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t1.webp",
  },
  {
    id: 8,
    name: "ROGER SCOTT",
    post: "AMAZON",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t3.webp",
  },
  {
    id: 9,
    name: "ROGER SCOTT",
    post: "HOTSTAR",
    desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
    cover: "./images/testo/t1.webp",
  },
]

export const explore_mentors = [
  {
    id: 1,
    name: "Alice Johnson",
    image: "https://i.pravatar.cc/300?img=47",
    job: "Frontend Developer",
    description: "Alice is a skilled Frontend Developer with over 5 years of experience in the tech industry. She has a passion for creating beautiful and functional user interfaces.",
    companies: "Amazon, Facebook, Oracle",
  },
  {
    id: 2,
    name: "Sophie Turner",
    image: "https://i.pravatar.cc/300?img=48",
    job: "Frontend Developer",
    description: "Sophie is an experienced Frontend Developer who loves bringing designs to life. She specializes in React and has worked with top design teams.",
    companies: "Google, Apple, Adobe",
  },
  {
    id: 3,
    name: "Chris Evans",
    image: "https://i.pravatar.cc/300?img=49",
    job: "Frontend Developer",
    description: "Chris is a passionate Frontend Developer with expertise in Angular. He has a background in graphic design, making him a unique asset in UI/UX development.",
    companies: "Netflix, Spotify, Dropbox",
  },
  {
    id: 4,
    name: "Bob Smith",
    image: "https://i.pravatar.cc/300?img=50",
    job: "Backend Developer",
    description: "Bob specializes in backend development and has a strong background in building scalable server-side applications. He has worked with some of the largest tech companies.",
    companies: "Google, Microsoft, IBM",
  },
  {
    id: 5,
    name: "Daniel Radcliffe",
    image: "https://i.pravatar.cc/300?img=51",
    job: "Backend Developer",
    description: "Daniel is a backend development expert, particularly in Java and Node.js. He has built robust systems for various high-traffic applications.",
    companies: "Amazon, LinkedIn, Twitter",
  },
  {
    id: 6,
    name: "Sarah Connor",
    image: "https://i.pravatar.cc/300?img=52",
    job: "Backend Developer",
    description: "Sarah excels in backend development, focusing on Python and Django frameworks. She has a strong background in data management and APIs.",
    companies: "Facebook, PayPal, Slack",
  },
  {
    id: 7,
    name: "Carol Davis",
    image: "https://i.pravatar.cc/300?img=53",
    job: "Full Stack Developer",
    description: "Carol is a versatile Full Stack Developer who can handle both frontend and backend tasks. She enjoys solving complex problems and optimizing performance.",
    companies: "Netflix, LinkedIn, Adobe",
  },
  {
    id: 8,
    name: "Michael Jordan",
    image: "https://i.pravatar.cc/300?img=54",
    job: "Full Stack Developer",
    description: "Michael is a dedicated Full Stack Developer with a knack for integrating modern front-end frameworks with robust backend services.",
    companies: "Spotify, Airbnb, Pinterest",
  },
  {
    id: 9,
    name: "Laura Palmer",
    image: "https://i.pravatar.cc/300?img=55",
    job: "Full Stack Developer",
    description: "Laura is a seasoned Full Stack Developer with experience in both MEAN and MERN stacks. She has worked on numerous high-profile projects.",
    companies: "Uber, Lyft, Salesforce",
  },
  {
    id: 10,
    name: "David Lee",
    image: "https://i.pravatar.cc/300?img=56",
    job: "Mobile Developer",
    description: "David is an expert in mobile development with extensive experience in creating high-quality mobile applications for both iOS and Android platforms.",
    companies: "Apple, Samsung, Huawei",
  },
  {
    id: 11,
    name: "Olivia Brown",
    image: "https://i.pravatar.cc/300?img=57",
    job: "Mobile Developer",
    description: "Olivia has over 7 years of experience in mobile app development, specializing in Swift and Kotlin. She has developed top-rated apps across various industries.",
    companies: "Google, Facebook, Snap",
  },
  {
    id: 12,
    name: "Eve Martin",
    image: "https://i.pravatar.cc/300?img=58",
    job: "UI/UX Designer",
    description: "Eve is a creative UI/UX Designer who focuses on creating user-friendly and aesthetically pleasing interfaces. She has a keen eye for detail and design.",
    companies: "Spotify, Airbnb, Pinterest",
  },
  {
    id: 13,
    name: "James Carter",
    image: "https://i.pravatar.cc/300?img=59",
    job: "UI/UX Designer",
    description: "James is an innovative UI/UX Designer with a strong background in user research and prototyping. He has a talent for creating engaging user experiences.",
    companies: "Microsoft, Adobe, Intel",
  },
  {
    id: 14,
    name: "Frank Brown",
    image: "https://i.pravatar.cc/300?img=60",
    job: "DevOps Engineer",
    description: "Frank is a seasoned DevOps Engineer with a deep understanding of continuous integration and continuous deployment. He ensures smooth and efficient operations.",
    companies: "Uber, Lyft, Dropbox",
  },
  {
    id: 15,
    name: "Grace Wilson",
    image: "https://i.pravatar.cc/300?img=61",
    job: "Data Scientist",
    description: "Grace is a Data Scientist who excels in data analysis and machine learning. She has a knack for uncovering insights from large datasets and making data-driven decisions.",
    companies: "Facebook, Twitter, Snapchat",
  },
  {
    id: 16,
    name: "Samuel Jackson",
    image: "https://i.pravatar.cc/300?img=62",
    job: "Data Scientist",
    description: "Samuel is an experienced Data Scientist with a focus on predictive modeling and data visualization. He has contributed to numerous groundbreaking studies.",
    companies: "Netflix, IBM, NASA",
  },
  {
    id: 17,
    name: "Henry White",
    image: "https://i.pravatar.cc/300?img=63",
    job: "Cloud Engineer",
    description: "Henry is an experienced Cloud Engineer with expertise in cloud infrastructure and services. He helps companies migrate to the cloud and optimize their cloud environments.",
    companies: "AWS, Google Cloud, Azure",
  },
  {
    id: 18,
    name: "Ivy Green",
    image: "https://i.pravatar.cc/300?img=64",
    job: "AI Engineer",
    description: "Ivy is an AI Engineer who specializes in developing artificial intelligence solutions. She has a strong background in machine learning and neural networks.",
    companies: "OpenAI, DeepMind, IBM",
  },
  {
    id: 19,
    name: "Jack Taylor",
    image: "https://i.pravatar.cc/300?img=65",
    job: "Cybersecurity Specialist",
    description: "Jack is a Cybersecurity Specialist with a focus on protecting systems and data from cyber threats. He has a wealth of experience in security protocols and practices.",
    companies: "NSA, FBI, Cisco",
  },
  {
    id: 20,
    name: "Kelly Moore",
    image: "https://i.pravatar.cc/300?img=66",
    job: "Blockchain Developer",
    description: "Kelly is a Blockchain Developer who works on creating decentralized applications and smart contracts. She is passionate about blockchain technology and its potential.",
    companies: "Ethereum, Ripple, ConsenSys",
  },
  {
    id: 21,
    name: "Liam Harris",
    image: "https://i.pravatar.cc/300?img=67",
    job: "AR/VR Developer",
    description: "Liam is an AR/VR Developer with expertise in creating immersive augmented and virtual reality experiences. He enjoys pushing the boundaries of what's possible in AR/VR.",
    companies: "Oculus, Magic Leap, HTC",
  },
];
